services:
    legobuilder.engine:
        class: Legobuilder\Prestashop\Engine\LegobuilderEngine
        public: true
        arguments:
            - '@legobuilder.engine.smarty_renderer'
            - '@legobuilder.database.database_adapter'
            - '@legobuilder.endpoint'
            - '@prestashop.core.hook.dispatcher'

    legobuilder.engine.smarty_renderer:
        class: Legobuilder\Prestashop\Engine\SmartyRenderer
        arguments:
            - '@prestashop.smarty'

    legobuilder.database.database_adapter:
        class: Legobuilder\Prestashop\Database\Adapter\PrestashopDatabaseAdapter
        arguments:
            - '@doctrine.dbal.default_connection'

    legobuilder.endpoint:
        class: Legobuilder\Prestashop\Endpoint\BuilderEndpoint