version: '3.1'

services:
    database:
        container_name: legobuilder_database
        image: mariadb:10.7.8
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=legobuilder
        volumes:
            - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - database_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: legobuilder_phpmyadmin
        ports:
            - 81:80
        depends_on:
            - database
        environment:
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=legobuilder

    prestashop:
        container_name: legobuilder_prestashop
        build:
            dockerfile: .docker/Dockerfile.ps
        depends_on:
            - database
        ports:
            - 80:80
        environment:
            - DB_USER=root
            - DB_PASSWD=legobuilder
            - DB_NAME=legobuilder_ps
            - DB_SERVER=database
            - PS_INSTALL_AUTO=1
            - PS_DOMAIN=localhost
            - PS_FOLDER_INSTALL=install-dev
            - PS_FOLDER_ADMIN=admin-dev
            - ADMIN_MAIL=legobuilder@legobuilder.com
            - ADMIN_PASSWD=legobuilder
            - LEGOBUILDER_VITE=5173
        volumes:
            - prestashop_data:/var/www/html
            - ./modules/prestashop:/var/www/html/modules/legobuilder
            - ./framework:/var/www/legobuilder-framework/
        
networks:
    app_network:
        external: true

volumes:
    database_data:
    prestashop_data:
