imports:
    - { resource: ../vendor/legobuilder/framework/src/Ressources/config/common.yml }

services:
    # Engine
    legobuilder.engine:
        class: Legobuilder\Engine\LegobuilderEngine
        public: true
        arguments:
            - '@legobuilder.framework.widget.widget_definition_registry'

    # Repository
    Legobuilder\Database\AbstractDatabaseAware:
        abstract:  true
        arguments: 
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    legobuilder.repository.doctrine_widget_repository:
        class: Legobuilder\Database\Repository\WidgetRepository
        parent: Legobuilder\Database\AbstractDatabaseAware
        
    Legobuilder\Framework\Persistence\Repository\WidgetRepositoryInterface:
        alias: 'legobuilder.repository.doctrine_widget_repository'
        public: true