imports:
    - { resource: ../vendor/legobuilder/framework/src/Ressources/config/common.yml }

services:
    # Engine
    legobuilder.widget.widget_definition_registry:
        class: Legobuilder\WidgetDefinition\Registry\WidgetDefinitionRegistry

    Legobuilder\Framework\WidgetDefinition\Registry\WidgetDefinitionRegistryInterface:
        alias: 'legobuilder.widget.widget_definition_registry'
        public: true

    # Repository
    Legobuilder\Database\AbstractDatabaseAware:
        abstract:  true
        arguments: 
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    legobuilder.repository.doctrine_widget_repository:
        class: Legobuilder\Database\Repository\WidgetRepository
        parent: Legobuilder\Database\AbstractDatabaseAware
        
    Legobuilder\Framework\Persistence\Repository\WidgetRepositoryInterface:
        alias: 'legobuilder.repository.doctrine_widget_repository'
        public: true

