services:
    legobuilder.engine:
        class: Legobuilder\Engine\LegobuilderEngine
        public: true
        arguments:
            - '@legobuilder.engine.smarty_renderer'
            - '@prestashop.core.hook.dispatcher'

    legobuilder.engine.smarty_renderer:
        class: Legobuilder\Engine\SmartyRenderer
        arguments:
            - '@prestashop.smarty'

    legobuilder.database.database_adapter:
        class: Legobuilder\Database\Adapter\PrestashopDatabaseAdapter
        arguments:
            - '@doctrine.dbal.default_connection'