services:
    legobuilder.engine:
        class: Legobuilder\Engine\LegobuilderEngine
        public: true
        arguments:
            - '@legobuilder.engine.smarty_renderer'
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    legobuilder.engine.smarty_renderer:
        class: Legobuilder\Renderer\SmartyRenderer
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getSmarty()'