services:
    legobuilder.engine:
        class: Legobuilder\Prestashop\Engine\LegobuilderEngine
        public: true
        arguments:
            - '@legobuilder.engine.smarty_renderer'
            - '@legobuilder.database.database_bridge'
            - '@prestashop.core.hook.dispatcher'

    legobuilder.engine.smarty_renderer:
        class: Legobuilder\Prestashop\Engine\SmartyRenderer
        arguments:
            - '@prestashop.smarty'

    legobuilder.database.database_bridge:
        class: Legobuilder\Prestashop\Database\PrestashopDatabaseBridge
        arguments:
            - '@doctrine.dbal.default_connection'
