services:
    legobuilder.engine:
        class: Legobuilder\Engine\LegobuilderEngine
        public: true
        arguments:
            - '@legobuilder.repository.widget_repository'

    Legobuilder\Database\AbstractDatabaseAware:
        abstract:  true
        arguments: 
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'
    
    legobuilder.repository.widget_repository:
        class: Legobuilder\Database\Repository\WidgetRepository
        parent: Legobuilder\Database\AbstractDatabaseAware
    