# Dissalow creating blank issues.
# blank_issues_enabled: false

contact_links:
  - name: Share and discuss ideas
    url: https://discord.gg/VXqGyT8
    about: Discuss any idea related to improving Bannerlord Coop

  - name: Website related
    url: https://github.com/Bannerlord-Coop-Team/BannerlordCoop-website
    about: Report bugs related to the website
