# Dissalow creating blank issues.
# blank_issues_enabled: false

contact_links:
  - name: Share and discuss ideas
    url: https://github.com/ca-joue-ce-soir/legobuilder/discussions
    about: Discuss any idea related to improving Lego builder