services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Legobuilder\Framework\Endpoint\Type\:
        resource: '../../Endpoint/Type/*'
        tags: ['endpoint_type']

    type_loader:
        class: 'Legobuilder\Framework\Endpoint\Loader\TypeLoader'
        arguments:
            - !tagged_locator endpoint_type