services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Legobuilder\Framework\Endpoint\Type\:
        resource: '../../Endpoint/Type/*'
        tags: ['endpoint.type']

    endpoint_type_loader:
        class: 'Legobuilder\Framework\Endpoint\Loader\DependecyInjectionTypeLoader'
        arguments:
            - !tagged_locator endpoint.type