imports:
    - { resource: ../../vendor/legobuilder/framework/src/Ressources/config/endpoint.yml }
    - { resource: ../common.yml }

services:
    # Controller
    Legobuilder\Controller\BuilderController:
        class: Legobuilder\Controller\BuilderController
        public: true
        arguments:
            - '@prestashop.adapter.shop.url.base_url_provider'