FROM php:7.4.33-zts-alpine

# Install node, composer and unzip packages
RUN apk update && apk add nodejs npm && apk add unzip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Create and define the application's working directory.
RUN mkdir /usr/src/legobuilder
WORKDIR /usr/src/legobuilder

CMD npm ci \
    && composer install -d framework  \
    && composer install -d modules/prestashop \
    && npm run dev