FROM prestashop/prestashop:8.0.3

RUN pecl install xdebug-3.1.3 \ 
    && docker-php-ext-enable xdebug	\
    && echo "xdebug.mode=profile,debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=trigger" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.profiler_output_name=cachegrind.out.%R" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer && rm -rf /tmp/composer-setup.php
RUN apt-get update && apt-get install -y nodejs npm unzip

COPY framework /var/www/legobuilder-framework
COPY modules/prestashop /var/www/html/modules/legobuilder

CMD bash -c "composer install --working-dir /var/www/html/modules/legobuilder && /tmp/docker_run.sh"