services:
    legobuilder.framework.widget.widget_factory:
        class: 'Legobuilder\Framework\Widget\Factory\WidgetFactory'
        arguments:
            - '@legobuilder.framework.repository.widget_repository'
            - '@legobuilder.framework.widget.widget_definition_registry'

    Legobuilder\Framework\Widget\Factory\WidgetFactoryInterface:
        alias: 'legobuilder.framework.widget.widget_factory'
        public: true
    
    legobuilder.framework.widget.widget_definition_registry:
        class: 'Legobuilder\Framework\WidgetDefinition\Registry\WidgetDefinitionRegistry'

    Legobuilder\Framework\WidgetDefinition\Registry\WidgetDefinitionRegistryInterface:
        alias: 'legobuilder.framework.widget.widget_definition_registry'
        public: true