services:
    legobuilder.framework.zone.zone_factory:
        class: 'Legobuilder\Framework\Engine\Zone\Factory\ZoneFactory'
        arguments:
            - '@legobuilder.framework.repository.widget_repository'
            - '@legobuilder.framework.widget.widget_factory'

    Legobuilder\Framework\Engine\Zone\Factory\ZoneFactoryInterface:
        alias: 'legobuilder.framework.zone.zone_factory'
        public: true