name: PrestaShop

on: 
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
    contents: read

jobs:
    bootstrap:
        name: Bootstrap
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            -   name: Install framework dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: 7.4
                    working_dir: framework
                    dev: yes
                    progress: yes

            -   name: Node bootstrap
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Install Node dependencies 
                run: npm ci

    release:
        needs: bootstrap
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            -   name: Build editor
                run: npm run build

            -   name: Copy editor dist
                run: | 
                    ls ${{ github.workspace }}
                    cp -vr ./editor/client/dist/ ./modules/prestashop/views/
                    
            -   name: Upload artifact
                uses: actions/upload-artifact@v3
                with:
                    name: prestashop-${{github.ref_name}}
                    path: modules/prestashop/
