services:
    _defaults:
        autowire: true
        autoconfigure: true

    Legobuilder\Framework\Endpoint\Type\:
        resource: '../../Endpoint/Type/*'
        tags: ['endpoint.type']

    Legobuilder\Framework\Endpoint\Type\Scalar\:
        resource: '../../Endpoint/Type/Scalar/*'
        tags: ['endpoint.type']

    Legobuilder\Framework\Endpoint\Resolver\:
        resource: '../../Endpoint/Resolver/*'

    Legobuilder\Framework\Endpoint\Mutator\:
        resource: '../../Endpoint/Mutator/*'

    endpoint.type_loader:
        class: 'Legobuilder\Framework\Endpoint\Loader\DependencyInjectionTypeLoader'
        arguments:
            - !tagged_locator endpoint.type

    Legobuilder\Framework\Endpoint\Loader\TypeLoaderInterface:
        alias: 'endpoint.type_loader'
        public: true

    endpoint:
        class: 'Legobuilder\Framework\Endpoint\DependencyInjectionEndpoint'
        arguments:
            - '@endpoint.type_loader'

    Legobuilder\Framework\Endpoint\EndpointInterface:
        alias: 'endpoint'
        public: true